name: 🐞 Report a new Bug
description: If you found a new bug on daisyUI package, report it here.
title: "bug: "
body:
  - type: markdown
    attributes:
      value: |
        ℹ️ Please first search in [existing issues](https://github.com/saadeghi/daisyui/issues?q=is%3Aissue) and [discussion forum](https://github.com/saadeghi/daisyui/discussions) and make sure this bug is not addressed before.
        ℹ️ Also see [FAQ / Common problems and how to fix](https://github.com/saadeghi/daisyui/discussions/1949). You may find your answer there.
  - type: input
    id: version
    attributes:
      label: What version of daisyUI are you using?
      description: You can see the daisyUI version number on your `package.json` file.
      placeholder: "example: v3.0.1"
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      description: |
        ℹ️ Describe the problem and say how and when it happens.
        ℹ️ To write a code block, use ``` before and after your code. Like this:
        ```
        code here
        ```
        ⚠️ Please don't use screenshots for code. Use code blocks instead.
        ⚠️ Please don't use JSX or Vue or any other framework specific code. Use plain HTML and CSS.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - All browsers
        - Chrome
        - Safari
        - Firefox
        - Edge
        - Safari iOS
        - Chrome Android
        - Other
  - type: input
    id: reproduction
    attributes:
      label: Reproduction URL
      description: |
        ℹ️ If you provide a link to a minimal [Tailwind Play](https://daisyui.com/tailwindplay/) page or a Stackblitz project or a public GitHub repo so we can reproduce the issue, we can help with this issue faster. Otherwise it can be hard to guess what is the cause of the problem and it will take more time to fix.
      placeholder: "https://"
    validations:
      required: false
