name: 🐞 Report a new Bug
description: If you found a new bug on daisyUI package, report it here.
title: "bug: "
body:
  - type: markdown
    attributes:
      value: |

        Thank you for submitting a bug report.  
        If you need help about your project and it's **NOT** a daisyUI bug, please [ask your question in discussion forum](https://github.com/saadeghi/daisyui/discussions/new?category=q-a).

  - type: checkboxes
    attributes:
      label: 1. Checklist
      options:
        - label: "I updated daisyUI (`npm i -D daisyui@latest`) but I still have this issue"
          required: true
        - label: "I looked up into [FAQ](https://github.com/saadeghi/daisyui/discussions/1949) but I couldn't find a solution"
          required: true
        - label: "I searched in [existing issues](https://github.com/saadeghi/daisyui/issues?q=is%3Aissue) and [discussion forum](https://github.com/saadeghi/daisyui/discussions?discussions_q=) but this bug has not addressed before"
          required: true
        - label: This bug is dasiyUI issue and it's **NOT** specific to a JS framework or a build tool."
          required: true

  - type: input
    id: version
    attributes:
      label: 2. What version of daisyUI are you using?
      description: You can see the daisyUI version number on your `package.json` file.
      placeholder: "example: v3.9.1"
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: 3. Which browsers are you seeing the problem on?
      multiple: true
      options:
        - All browsers
        - Chrome
        - Chrome Android
        - Safari
        - Safari iOS
        - Firefox
        - Edge
        - Other

  - type: input
    id: reproduction
    attributes:
      label: 4. Reproduction URL
      description: |

        ℹ️ Please provide a link to a small, minimal example source code where issue can be reproduced. Without a link it will be hard to guess what is the cause of the problem and it will take more time to fix.

        ℹ️ You can use a [Tailwind Play](https://daisyui.com/tailwindplay/) page or a [Stackblitz page](https://stackblitz.com/@saadeghi/collections/daisyui) or a public GitHub repo.

        ℹ️ If the issue doesn't happen on [Tailwind Play](https://daisyui.com/tailwindplay/) it means it's not an issue from daisyUI.  
        It can be a config problem in your project ([ask here](https://github.com/saadeghi/daisyui/discussions?discussions_q=)) or it can be an issue from your framework or CSS build tools.

      placeholder: "https://"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 5. Describe your issue
      description: |

        ℹ️ Describe the problem and say how and when it happens.

        ℹ️ To write a code block, use ``` before and after your code.

        ⚠️ Please don't use JSX or other framework specific code. Use plain HTML and CSS.

    validations:
      required: true
