name: "📘 Deploy docs"

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
    paths:
      - "src/docs/**"
  workflow_run:
    workflows:
      - "🎉 Release new version"
    types:
      - completed

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "latest"
      #     registry-url: https://registry.npmjs.org

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install package dependencies
        run: bun install

      - name: Build package (skip cdn files)
        run: bun run build:skipcdnfiles

      - name: Install docs dependencies
        run: cd src/docs && bun install

      - name: Install alpha daisyUI if staging
        if: github.repository == 'daisyui/daisyui.github.io'
        run: cd src/docs && bun i daisyui@alpha

      - name: Install latest daisyUI if production
        if: github.repository == 'saadeghi/daisyui'
        run: cd src/docs && bun i daisyui@latest

      - name: get new data from API
        run: cd src/docs && bun run get-files

      - name: Build docs
        run: cd src/docs && bun run build

      - name: Deploy docs to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/docs/build
          cname: ${{ secrets.CNAME }}
