name: "📘 Deploy docs"

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
    paths:
      - "src/docs/**"
      - "CHANGELOG.md"

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          registry-url: https://registry.npmjs.org

      - name: Install package dependencies
        run: npm install

      - name: build package
        run: npm run build

      - name: Install docs dependencies
        run: cd src/docs && npm install

      - name: Install alpha daisyUI if staging
        if: github.repository == 'daisyui/daisyui.github.io'
        run: cd src/docs && npm i daisyui@alpha

      - name: Install latest daisyUI if production
        if: github.repository == 'saadeghi/daisyui'
        run: cd src/docs && npm i daisyui@latest

      - name: get new data from API
        run: cd src/docs && npm run get-files

      - name: Build docs
        run: cd src/docs && npm run build

      - name: Deploy docs to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/docs/build
          cname: ${{ secrets.CNAME }}
