name: "📘 Deploy docs"

on:
  workflow_dispatch:
    inputs:
      npm-tag:
        type: choice
        description: Version of daisyUI to install
        default: "latest"
        options:
          - "latest"
          - "alpha"
  workflow_call:
  push:
    branches:
      - master
    paths:
      - "src/docs/**"
  workflow_run:
    workflows:
      - "🎉 Release new version"
    types:
      - completed

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'workflow_call' ||
      github.event_name == 'push' ||
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "latest"
      #     registry-url: https://registry.npmjs.org

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install package dependencies
        run: bun install

      - name: Build package (skip cdn file)
        run: bun run build:skipcdnfiles

      - name: Install docs dependencies
        run: cd src/docs && bun install

      - name: Install daisyUI
        run: cd src/docs && bun i daisyui@${{ github.event.inputs.npm-tag }}

      - name: Get new data from API
        run: cd src/docs && bun run get-files

      - name: Build docs
        run: cd src/docs && bun run build

      - name: Deploy docs to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/docs/build
          cname: ${{ secrets.CNAME }}
