name: "Release"

on:
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          registry-url: https://registry.npmjs.org

      - name: Install package dependencies
        run: npm install

      - name: Release
        run: |
          git config --local user.email "pouya.saadeghi@gmail.com"
          git config --local user.name "Pouya Saadeghi"
          npm run release

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        uses: saadeghi/daisyui/.github/workflows/build-publish-deploy.yml@master
