name: "🎉 Release new version"

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: Release type
        options:
          - ":patch"
          - ":minor"
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "!src/docs/**"
      - "!src/tests/**"
      - "!src/experiments/**"

jobs:
  release:
    if: github.repository == 'saadeghi/daisyui'
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          registry-url: https://registry.npmjs.org

      # - name: Setup bun
      #   uses: oven-sh/setup-bun@v1

      - name: Install package dependencies
        run: npm install

      - name: Release
        run: |
          git config --local user.email "pouya.saadeghi@gmail.com"
          git config --local user.name "Pouya Saadeghi"
          npm run release${{ github.event.inputs.release-type }}

      - name: build package
        run: npm run build

      - name: get-npm-version
        id: package-version
        # uses: martinbeentjes/npm-get-version-action@v1
        run: |
          echo current-version=$(grep -o '"version": *"[^"]*"' package.json | cut -d'"' -f4) >> $GITHUB_OUTPUT

      - name: update package version in env
        run: echo "VITE_DAISYUI_VERSION=${{ steps.package-version.outputs.current-version }}" > src/docs/.env

      - name: Commit files
        id: commit
        run: |
          git config --local user.email "pouya.saadeghi@gmail.com"
          git config --local user.name "Pouya Saadeghi"
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "push=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Update version: ${{ steps.package-version.outputs.current-version }}" -a
            echo "push=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
