name: "🧪 Tests"

on:
  workflow_dispatch:
    inputs:
      filter:
        type: choice
        description: Filter tests
        default: " "
        options:
          - " "
          - "-t framework"
          - "-t contrast"
          - "-t foreground"
          - "-t variables"
          - "-t colors"
  push:
    branches:
      - master
    paths:
      - "src/theming/**"
jobs:
  tests:
    env:
      filter: ${{ github.event.inputs.filter || ' '}}
    timeout-minutes: 10
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install package dependencies
        run: bun install

      - name: build package
        run: bun run build:skipfullcss

      - name: Run tests
        run: bun test ${{ env.filter }}
